### PR TITLE
Proper sourcemod search on Linux

### LINKED ISSUE #2: Use registry.vdf file to get sourcemod path on Linux

### PR DESCRIPTION
**Pull request by Alex-1000**
No longer searching by common locations, using registry.vdf instead.

Fixes #2

### CODE REVIEW

**Comment by chloecormier** [comment]
Don't include your changes to README.md, then I'm fine merging.

**Comment by Alex-1000** [comment]
for whatever reason github doesnt allow to revert commits from website
anyway i fixed it

**Comment by chloecormier** [comment]
Still has some remnants, but it's fine, I'll just edit them out after merging.

**Comment by Technochips** [comment]
"Self-developed improvements for TF2 Classic downloader" what in the hell does that mean in the context of the official downloader

**Comment by Alex-1000** [comment]
I didn't think that pull request would include edits made after request

**Pull request merged**
